import type { AnalysisResult, TranscriptSegment } from "./types";

/** Dev-only sample for the /?demo=1 UI preview. Not used in production. */
export const SAMPLE_SEGMENTS: TranscriptSegment[] = [
  {
    id: 1,
    speaker: "S1",
    start: 0,
    end: 4.2,
    text: "Hello, this is Kwame from MTN customer care.",
    words: [
      { w: "Hello,", start: 0, end: 0.5 },
      { w: "this", start: 0.6, end: 0.9 },
      { w: "is", start: 0.9, end: 1.1 },
      { w: "Kwame", start: 1.2, end: 1.7 },
      { w: "from", start: 1.8, end: 2.1 },
      { w: "MTN", start: 2.2, end: 2.9 },
      { w: "customer", start: 3.0, end: 3.6 },
      { w: "care.", start: 3.6, end: 4.2 },
    ],
  },
  {
    id: 2,
    speaker: "S1",
    start: 5,
    end: 10.4,
    text: "Congratulations! You have won free money in our MoMo promotion.",
    words: [
      { w: "Congratulations!", start: 5, end: 6 },
      { w: "You", start: 6.2, end: 6.5 },
      { w: "have", start: 6.5, end: 6.8 },
      { w: "won", start: 6.9, end: 7.3 },
      { w: "free", start: 7.4, end: 7.8 },
      { w: "money", start: 7.9, end: 8.4 },
      { w: "in", start: 8.5, end: 8.8 },
      { w: "our", start: 8.9, end: 9.2 },
      { w: "MoMo", start: 9.3, end: 9.8 },
      { w: "promotion.", start: 9.9, end: 10.4 },
    ],
  },
  {
    id: 3,
    speaker: "S2",
    start: 12,
    end: 14.5,
    text: "Really? How much did I win?",
    words: [
      { w: "Really?", start: 12, end: 12.8 },
      { w: "How", start: 13, end: 13.3 },
      { w: "much", start: 13.3, end: 13.7 },
      { w: "did", start: 13.8, end: 14 },
      { w: "I", start: 14, end: 14.2 },
      { w: "win?", start: 14.2, end: 14.5 },
    ],
  },
  {
    id: 4,
    speaker: "S1",
    start: 15.5,
    end: 22,
    text: "Five thousand cedis. To release it, we just sent a code to your phone. Read me the code now.",
    words: [
      { w: "Five", start: 15.5, end: 15.9 },
      { w: "thousand", start: 16, end: 16.5 },
      { w: "cedis.", start: 16.6, end: 17.2 },
      { w: "To", start: 17.6, end: 17.9 },
      { w: "release", start: 18, end: 18.5 },
      { w: "it,", start: 18.5, end: 18.9 },
      { w: "we", start: 19, end: 19.3 },
      { w: "just", start: 19.4, end: 19.7 },
      { w: "sent", start: 19.8, end: 20.2 },
      { w: "a", start: 20.3, end: 20.4 },
      { w: "code", start: 20.5, end: 20.9 },
      { w: "to", start: 21, end: 21.2 },
      { w: "your", start: 21.3, end: 21.5 },
      { w: "phone.", start: 21.6, end: 21.9 },
      { w: "Read", start: 22.4, end: 22.7 },
      { w: "me", start: 22.7, end: 22.9 },
      { w: "the", start: 23, end: 23.2 },
      { w: "code", start: 23.3, end: 23.7 },
      { w: "now.", start: 23.8, end: 24.2 },
    ],
  },
  {
    id: 5,
    speaker: "S1",
    start: 25,
    end: 29.5,
    text: "Hurry, the code expires in two minutes or the money goes to someone else.",
    words: [
      { w: "Hurry,", start: 25, end: 25.6 },
      { w: "the", start: 25.8, end: 26 },
      { w: "code", start: 26.1, end: 26.5 },
      { w: "expires", start: 26.6, end: 27.2 },
      { w: "in", start: 27.3, end: 27.5 },
      { w: "two", start: 27.6, end: 27.9 },
      { w: "minutes", start: 28, end: 28.5 },
      { w: "or", start: 28.6, end: 28.8 },
      { w: "the", start: 28.9, end: 29.1 },
      { w: "money", start: 29.2, end: 29.5 },
      { w: "goes", start: 29.6, end: 29.9 },
      { w: "to", start: 30, end: 30.2 },
      { w: "someone", start: 30.3, end: 30.7 },
      { w: "else.", start: 30.8, end: 31.2 },
    ],
  },
];

export const SAMPLE_RESULT: AnalysisResult = {
  verdict: "scam",
  confidence: 96,
  headline: "Caller fakes an MTN promo to steal your MoMo one-time code.",
  explanation:
    "The caller claims you won free money, then asks you to read back a code sent to your phone. That code is a MoMo authorization OTP, and reading it out hands over your wallet. MTN never asks for codes over the phone. The urgency ('expires in two minutes') is a classic pressure tactic.",
  evidence: [
    {
      title: "Asks you to read out a one-time code",
      why: "Real MTN staff never ask for OTP or PIN codes. That code authorizes access to your MoMo wallet.",
      quote: "we just sent a code to your phone. Read me the code now.",
      segmentIds: [4],
      severity: "high",
    },
    {
      title: "Fake prize claim",
      why: "'You won free money' is the standard hook for MoMo promo scams. No such promotion was found in official MTN announcements.",
      quote: "You have won free money in our MoMo promotion.",
      segmentIds: [2],
      severity: "high",
    },
    {
      title: "Urgency pressure",
      why: "A fake deadline pushes you to act before thinking or checking with MTN.",
      quote: "the code expires in two minutes or the money goes to someone else.",
      segmentIds: [5],
      severity: "medium",
    },
  ],
  claimChecks: [
    {
      claim: "MTN is running a MoMo promotion giving out free money",
      status: "false",
      finding:
        "No official MTN Ghana promotion matching this description was found; MTN warns customers about exactly this promo-impersonation scam.",
      sources: [
        { title: "MTN Ghana: Fraud awareness", url: "https://mtn.com.gh" },
      ],
    },
  ],
  supportNumbers: [
    {
      service: "MTN Ghana",
      number: "100",
      note: "Official MTN customer care short code (free from MTN lines).",
    },
  ],
  whatToDo: [
    "Hang up. Do not read any code to the caller.",
    "Never share OTPs, PINs, or MoMo codes on a call.",
    "Dial 100 to confirm with MTN directly.",
    "Report the caller's number below to warn others.",
  ],
  impersonatedService: "MTN MoMo",
  scamType: "otp_theft",
  numbersMentioned: ["024 555 0137"],
  priorReports: [{ number: "233245550137", count: 3 }],
  model: "gpt-oss-120b",
};
